### ISSUE TITLE
Generate an HTML file that links to all the thumbnails

### ISSUE THREAD

**Issue by bmann** [fission-suite/basquiat#1]
## Problem

The thumbnails are created, but aren't easily findable / browseable without running `ipfs object links` or URL hacking your gateway path.

### Impact

Requires users to do a lot of thinking and exploring to even see what this does.

## Solution

After generating all the thumbnails and outputing the image hash with linked thumbnails, create a second file, `thumbnails.html` which shows the original file and links / previews of all of the sized thumbnails.

On running the command, something like:

"Generated XX thumbnails, original image hash is Qm..."

"Thumbnail generated locally as `thumbnails.html`, and added to IPFS as https://localhost:8080/ipfs/Qm..."

**Comment by ellttBen** [comment]
Commit 302945e9a3f44d6a04ef502c24e2ade19b7ac0bf closes this issue by offering a `thumbnails.html` directly accessible through `<root_cid>/thumbnails.html`.
